const crypto=require('crypto');
const BASE='https://api.brevo.com/v3';
const SITE='https://www.maispersuasaomaisvendas.com.br';
const LIST_ID=Number(process.env.BREVO_LIST_ID||5), AULA_REG='MPMV_A17_REG', AULA_STAGE='MPMV_A17_ST';
const STEPS=[
{id:'n2',at:'2026-09-13T12:00:00Z',subject:'O que realmente faz alguém decidir comprar?',body:`{{nome}}, amanhã eu quero continuar uma conversa importante.\n\nPersuasão não começa quando você pede a venda. Começa muito antes: na forma como a pessoa percebe o problema, interpreta a oferta e avalia o risco de decidir.\n\nNa aula do dia 17, vou mostrar como usar isso para construir uma comunicação mais convincente sem transformar sua mensagem em um amontoado de gatilhos.\n\nQuero que você chegue à aula olhando para suas vendas de outro jeito.`},
{id:'n3',at:'2026-09-14T12:00:00Z',subject:'Seu cliente não compra só porque entendeu',body:`{{nome}}, entender uma oferta é diferente de querer comprá-la.\n\nUma pessoa pode entender perfeitamente o que você vende e ainda não sentir segurança suficiente para avançar.\n\nÉ aí que muita comunicação trava: explica benefício, apresenta mecanismo, mostra prova… mas não trabalha a percepção que antecede a decisão.\n\nNa aula ao vivo, vamos destrinchar essa diferença e colocar isso no contexto de conteúdo, anúncios e páginas.`},
{id:'n4',at:'2026-09-15T12:00:00Z',subject:'O problema pode não estar no seu tráfego',body:`{{nome}}, antes de colocar mais dinheiro em tráfego, existe uma pergunta que vale fazer: o que acontece depois que a pessoa chega?\n\nPorque mais cliques não corrigem uma oferta mal percebida. Mais alcance não resolve uma mensagem que não cria clareza. E mais conteúdo não garante decisão.\n\nPersuasão ajuda justamente a enxergar esse caminho.\n\nDia 17, às 19h, eu vou mostrar como pensar nessa jornada com mais precisão.`},
{id:'n5',at:'2026-09-16T12:00:00Z',subject:'Amanhã você vai poder olhar para sua comunicação com outros olhos',body:`{{nome}}, é amanhã.\n\nNa aula, eu não vou te entregar uma lista de frases mágicas para copiar. Quero te mostrar o raciocínio por trás de uma comunicação persuasiva: o que a pessoa percebe, o que ela precisa entender e por que decide avançar.\n\nSepare um papel, abra suas campanhas ou sua página principal e venha com uma pergunta em mente: “onde minha comunicação pode estar perdendo uma venda?”\n\nA gente começa às 19h.`},
{id:'today',at:'2026-09-17T11:00:00Z',subject:'É hoje: Aula ao Vivo MPMV às 19h',body:`{{nome}}, hoje é o dia.\n\nÀs 19h, começa a Aula ao Vivo MPMV.\n\nA proposta é simples: entender melhor como as pessoas percebem, avaliam e decidem — e transformar isso em comunicação que vende sem depender de pressão ou truques.\n\nReserve esse horário e deixe o acesso salvo. Nos vemos às 19h.`},
{id:'soon',at:'2026-09-17T21:30:00Z',subject:'Daqui a pouco: estamos começando às 19h',body:`{{nome}}, falta pouco.\n\nEm alguns minutos começa a Aula ao Vivo MPMV.\n\nSe você ainda não abriu o acesso, faça isso agora e deixe tudo pronto para acompanhar sem correria.\n\nNos vemos já já.`},
{id:'live',at:'2026-09-17T22:00:00Z',subject:'Estamos ao vivo agora',body:`{{nome}}, começou.\n\nA Aula ao Vivo MPMV está acontecendo agora.\n\nEntre pelo acesso e acompanhe ao vivo.\n\nTe vejo lá.`}
];
const key=()=>process.env.BREVO_API_KEY||process.env.BREVO_KEY||process.env.SENDINBLUE_API_KEY||'';
const clean=(v,n=10000)=>String(v==null?'':v).trim().slice(0,n);
const emailOk=v=>/^\S+@\S+\.\S+$/.test(clean(v,180));
const esc=v=>clean(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const json=(res,s,b)=>(res.setHeader('Cache-Control','no-store'),res.status(s).json(b));
async function brevo(path,opt={}){const r=await fetch(BASE+path,{...opt,headers:{accept:'application/json','api-key':key(),'content-type':'application/json',...(opt.headers||{})}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok){const e=new Error(d.message||`brevo_${r.status}`);e.status=r.status;throw e}return d}
async function sender(){const d=await brevo('/senders'),s=(d.senders||[]).find(x=>x&&x.email&&x.active!==false);if(!s)throw new Error('no_active_sender');return{email:s.email,name:s.name||'MPMV'}}
async function ensureAttrs(){const d=await brevo('/contacts/attributes'),have=new Set((d.attributes||[]).map(x=>String(x.name||'').toUpperCase()));for(const n of [AULA_REG,AULA_STAGE])if(!have.has(n))try{await brevo('/contacts/attributes/normal/'+n,{method:'POST',body:JSON.stringify({type:'text'})})}catch(e){if(e.status!==400)throw e}}
const fill=(s,c)=>String(s||'').replace(/\{\{nome\}\}/g,clean(c.attributes?.FIRSTNAME||'Olá',100));
const unsubToken=e=>crypto.createHmac('sha256',key()).update('mpmv-unsub:'+e).digest('hex').slice(0,32);
function render(step,c){const body=fill(step.body,c).split(/\n{2,}/).map(p=>`<p style="margin:0 0 18px;line-height:1.65;color:#17202a;font-size:16px">${esc(p).replace(/\n/g,'<br>')}</p>`).join('');const access=`<p style="margin:28px 0 18px"><a href="${SITE}/mentoria-ao-vivo/" style="display:inline-block;background:#ef5a63;color:#fff;text-decoration:none;font-weight:800;padding:14px 20px;border-radius:9px">ACESSAR A AULA</a></p>`;const u=`${SITE}/api/guia?action=aula-17-09-unsubscribe&email=${encodeURIComponent(c.email)}&t=${unsubToken(c.email)}`;return`<!doctype html><html><body style="margin:0;background:#f3f6f8;font-family:Arial,Helvetica,sans-serif"><table width="100%" cellspacing="0" cellpadding="0" style="background:#f3f6f8;padding:28px 12px"><tr><td align="center"><table width="100%" cellspacing="0" cellpadding="0" style="max-width:640px;background:#fff;border:1px solid #dfe7ec;border-radius:14px"><tr><td style="padding:28px 30px 10px;color:#0d6f9f;font-weight:900">MPMV — MAIS PERSUASÃO, MAIS VENDAS</td></tr><tr><td style="padding:10px 30px 10px">${body}${access}</td></tr><tr><td style="padding:10px 30px 28px;color:#71818b;font-size:12px;line-height:1.5">Você recebeu este e-mail porque se inscreveu na Aula ao Vivo MPMV.<br><a href="${u}" style="color:#71818b">Não quero mais receber estes avisos.</a></td></tr></table></td></tr></table></body></html>`}
async function send(step,c){return brevo('/smtp/email',{method:'POST',body:JSON.stringify({sender:await sender(),to:[{email:c.email,name:c.attributes?.FIRSTNAME||'Olá'}],subject:fill(step.subject,c),htmlContent:render(step,c)})})}
async function update(id,attributes){return brevo('/contacts/'+encodeURIComponent(String(id))+'?identifierType=contact_id',{method:'PUT',body:JSON.stringify({attributes})})}
async function register(name,email){await ensureAttrs();const p=name.trim().split(/\s+/),first=p.shift()||name,last=p.join(' '),reg=new Date().toISOString();try{await brevo('/contacts',{method:'POST',body:JSON.stringify({email,attributes:{FIRSTNAME:first,...(last?{LASTNAME:last}:{}),[AULA_REG]:reg,[AULA_STAGE]:'welcome'},listIds:[LIST_ID],updateEnabled:true})})}catch(e){if(e.status!==400)throw e;const old=await brevo('/contacts/'+encodeURIComponent(email));await update(old.id,{FIRSTNAME:first,...(last?{LASTNAME:last}:{}),[AULA_REG]:reg,[AULA_STAGE]:'welcome'})}const c=await brevo('/contacts/'+encodeURIComponent(email));await send({id:'welcome',subject:'Inscrição confirmada: Aula ao Vivo MPMV dia 17',body:`${first}, sua inscrição está confirmada.\n\nNo dia 17 de setembro, às 19h, você participa gratuitamente da Aula ao Vivo MPMV.\n\nAté lá, vou te enviar alguns e-mails curtos para preparar o olhar e fazer você chegar à aula já pensando nas suas próprias vendas.\n\nSalve o horário: 17 de setembro, 19h.`},{id:c.id,email,attributes:c.attributes||{FIRSTNAME:first}});return c}
async function cron(){await ensureAttrs();const d=await brevo(`/contacts/lists/${LIST_ID}/contacts?limit=500&offset=0&sort=desc`),cs=d.contacts||[],now=Date.now(),events=[];for(const c of cs){const a=c.attributes||{},reg=Date.parse(a[AULA_REG]||'');if(!Number(c.id)||!emailOk(c.email)||!Number.isFinite(reg))continue;let stage=String(a[AULA_STAGE]||'welcome');for(const s of STEPS){if(Date.parse(s.at)>now)break;const due=(s.id==='n2'&&stage==='welcome')||(s.id==='n3'&&stage==='n2')||(s.id==='n4'&&stage==='n3')||(s.id==='n5'&&stage==='n4')||(s.id==='today'&&stage==='n5')||(s.id==='soon'&&stage==='today')||(s.id==='live'&&stage==='soon');if(due){if(reg>Date.parse(s.at))continue;try{await send(s,c);await update(c.id,{[AULA_STAGE]:s.id});events.push({email:c.email,step:s.id,result:'sent'})}catch(e){events.push({email:c.email,step:s.id,result:'error',error:e.message})}break}}}return{ok:true,processed:cs.length,events}}
async function handleAula17(req,res){if(!key())return json(res,503,{ok:false,error:'brevo_not_configured'});const action=clean(req.query&&req.query.action,50);if(action==='aula-17-09-cron')return json(res,200,await cron());if(action==='aula-17-09-unsubscribe'){const email=clean(req.query&&req.query.email,180).toLowerCase(),t=clean(req.query&&req.query.t,100);if(!emailOk(email)||t!==unsubToken(email))return res.status(400).send('Link inválido.');const c=await brevo('/contacts/'+encodeURIComponent(email));await brevo('/contacts/'+encodeURIComponent(String(c.id))+'?identifierType=contact_id',{method:'PUT',body:JSON.stringify({emailBlacklisted:true})});return res.status(200).send('Tudo certo. Você não receberá mais estes avisos.')}if(action!=='aula-17-09')return null;if(req.method!=='POST')return json(res,405,{ok:false,error:'method_not_allowed'});try{const b=typeof req.body==='string'?JSON.parse(req.body):(req.body||{}),name=clean(b.name,80),email=clean(b.email,180).toLowerCase();if(name.length<2||!emailOk(email))return json(res,400,{ok:false,error:'invalid_lead'});const c=await register(name,email);return json(res,200,{ok:true,email:c.email})}catch(e){console.error('Aula 17/09 error',e);return json(res,e.status&&e.status<600?e.status:500,{ok:false,error:e.message||'internal_error'})}}
module.exports={handleAula17};